#!/bin/bash
C=/root/linux-next/.config
echo "=== options crypto requises par iwd ==="
for s in CONFIG_KEY_DH_OPERATIONS CONFIG_CRYPTO_USER_API_SKCIPHER CONFIG_CRYPTO_USER_API_HASH CONFIG_CRYPTO_USER_API CONFIG_CRYPTO_MD5 CONFIG_CRYPTO_SHA1 CONFIG_CRYPTO_SHA256 CONFIG_CRYPTO_SHA512 CONFIG_CRYPTO_HMAC CONFIG_CRYPTO_CMAC CONFIG_CRYPTO_AES CONFIG_CRYPTO_ECB CONFIG_CRYPTO_CBC CONFIG_CRYPTO_DES CONFIG_CRYPTO_ARC4 CONFIG_PKCS8_PRIVATE_KEY_PARSER CONFIG_ASYMMETRIC_KEY_TYPE CONFIG_KEYS CONFIG_CRYPTO_USER_API_AEAD CONFIG_CRYPTO_MD4; do
  v=$(grep -E "^$s=" "$C" 2>/dev/null || echo "$s=NON")
  printf '  %s\n' "$v"
done
